#Requerir al usuario que ingrese un número entero e informar si es primo o no,
#utilizando una función booleana que lo decida. (booleana quiere decir que
#devuelva true o false) 

#def es_primo(num):
 #   for n in range(2, num):
  #      if num % n == 0:
   #         print("No es primo", n, "es divisor")
    #        return False
   # print("Es primo")
    #return True

#num= int(input(("Ingrese un numero ")))

#es_primo(num)

#Solicitar al usuario el ingreso de números primos. La lectura finalizará cuando
#ingrese un número que no sea primo.

#def es_primo(num):
#    for n in range(2, num):
#        if num % n == 0:
#            print("No es primo", n, "es divisor")
#            return False
#    
#        print("Es primo")
#        return True
    
       
#num= int(input(("Ingrese un numero ")))    

#es_primo(num)
#---

#Escribir una función que, dado un número de DNI (el dni debe ser un string),
#retorne True si el número es válido y False si no lo es. Para que un número de
#DNI sea válido debe tener entre 7 y 8 dígitos

#def dni_correcto(dni):
  #  largo = len(dni)
  #  if largo==7 or largo==8:
  #      print("el dni es correcto")
  #      return True
   # else:
  #      print("el numero no es valido")
 #       return False
        
    
        
#dni=input("ingrese su dni ")
        
#dni_correcto(dni)

print(len("yanina"))